=== GregoryEAllen/cpn/libraries/xmlcpn/xml/cpn.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

    <xsd:element name="network">
	<xsd:complexType>
	    <xsd:sequence>
		<xsd:element ref="nodes"/>
		<xsd:element ref="queues"/>
	    </xsd:sequence>
	</xsd:complexType>
    </xsd:element>

    <xsd:element name="hosts">
	<xsd:complexType>
	    <xsd:sequence>
		<xsd:element ref="host" maxOccurs="unbounded"/>
	    </xsd:sequence>
	</xsd:complexType>
    </xsd:element>

    <xsd:element name="hostmap">
	<xsd:complexType>
	    <xsd:sequence>
		<xsd:element name="host" maxOccurs="unbounded">
		    <xsd:complexType>
			<xsd:sequence>
			    <xsd:element ref="name"/>
			    <xsd:element name="node" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		    </xsd:complexType>
		</xsd:element>
	    </xsd:sequence>
	</xsd:complexType>
    </xsd:element>

    <xsd:element name="hostprog">
	<xsd:complexType>
	    <xsd:sequence>
		<xsd:element ref="name"/>
		<xsd:element ref="hosttype"/>
		<xsd:element ref="hosts"/>
		<xsd:element ref="nodes"/>
		<xsd:element ref="queues"/>
	    </xsd:sequence>
	</xsd:complexType>
    </xsd:element>

    <xsd:element name="nodes">
	<xsd:complexType>
	    <xsd:sequence>
		<xsd:element ref="node" minOccurs="0" maxOccurs="unbounded"/>
	    </xsd:sequence>
	</xsd:complexType>
    </xsd:element>

    <xsd:element name="node">
	<xsd:complexType>
	    <xsd:sequence>
		<xsd:element ref="name"/>
		<xsd:element ref="type"/>
		<xsd:element ref="param" minOccurs="0"/>
	    </xsd:sequence>
	</xsd:complexType>
    </xsd:element>

    <!-- possible future tag a node type description describing things like
    what ports the node type has etc. -->
    <xsd:element name="nodetype">
	<xsd:complexType>
	    <xsd:sequence>
		<xsd:element ref="name"/>
		<xsd:element name="outport" type="nodeport" minOccurs="0" maxOccurs="unbounded"/>
		<xsd:element name="inport" type="nodeport" minOccurs="0" maxOccurs="unbounded"/>
	    </xsd:sequence>
	</xsd:complexType>
    </xsd:element>

    <xsd:complexType name="nodeport">
	<xsd:sequence>
	    <xsd:element ref="name"/>
	    <xsd:element ref="datatype"/>
	    <xsd:element ref="maxThreshold"/>
	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="queues">
	<xsd:complexType>
	    <xsd:sequence>
		<xsd:element ref="queue" minOccurs="0" maxOccurs="unbounded"/>
	    </xsd:sequence>
	</xsd:complexType>
    </xsd:element>

    <xsd:element name="queue">
	<xsd:complexType>
	    <xsd:sequence>
		<xsd:element ref="name"/>
		<xsd:element ref="type"/>
		<xsd:element ref="datatype"/>
		<xsd:element ref="size"/>
		<xsd:element ref="maxThreshold"/>
		<xsd:element ref="channels"/>
		<xsd:element name="writer" type="endpoint"/>
		<xsd:element name="reader" type="endpoint"/>
	    </xsd:sequence>
	</xsd:complexType>
    </xsd:element>

    <xsd:complexType name="endpoint">
	<xsd:sequence>
	    <xsd:element name="node" type="xsd:string"/>
	    <xsd:element name="port" type="xsd:string"/>
	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="host">
	<xsd:complexType>
	    <xsd:sequence>
		<xsd:element ref="name"/>
		<xsd:element ref="hosttype"/>
		<xsd:element name="connection" maxOccurs="unbounded">
		    <xsd:complexType>
			<xsd:sequence>
			    <xsd:element ref="type"/>
			    <xsd:element ref="param"/>
			</xsd:sequence>
		    </xsd:complexType>
		</xsd:element>
	    </xsd:sequence>
	</xsd:complexType>
    </xsd:element>

    <xsd:element name="name" type="xsd:string"/>
    <xsd:element name="type" type="xsd:string"/>
    <xsd:element name="param" type="xsd:string"/>
    <xsd:element name="hosttype">
	<xsd:simpleType>
	    <xsd:restriction base="xsd:string">
		<xsd:enumeration value="master"/>
		<xsd:enumeration value="slave"/>
	    </xsd:restriction>
	</xsd:simpleType>
    </xsd:element>
    <xsd:element name="datatype">
	<xsd:simpleType>
	    <xsd:restriction base="xsd:string">
		<xsd:pattern value="(complex_)?(u|s)?(int|float)(\d{1,3})"/>
	    </xsd:restriction>
	</xsd:simpleType>
    </xsd:element>
    <!-- maxThreshold should be <= size -->
    <xsd:element name="size" type="xsd:positiveInteger"/>
    <xsd:element name="maxThreshold" type="xsd:positiveInteger"/>
    <xsd:element name="channels" type="xsd:positiveInteger"/>
</xsd:schema>

=== GregoryEAllen/cpn/libraries/xmlcpn/xml/ExampleHosts.xml
<?xml version="1.0"?>
<hosts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="cpn.xsd">
    <host>
	<name>zeus</name>
	<hosttype>master</hosttype>
	<connection>
	    <type>tcpip</type>
	    <param>zeus.arlut.utexas.edu</param>
	</connection>
    </host>
    <host>
	<name>metis</name>
	<hosttype>slave</hosttype>
	<connection>
	    <type>tcpip</type>
	    <param>metis.arlut.utexas.edu</param>
	</connection>
    </host>
    <host>
	<name>syrinx</name>
	<hosttype>slave</hosttype>
	<connection>
	    <type>tcpip</type>
	    <param>syrinx.arlut.utexas.edu</param>
	</connection>
    </host>
</hosts>

=== GregoryEAllen/cpn/libraries/xmlcpn/xml/ExampleHostprog_zeus.xml
<?xml version="1.0"?>
<hostprog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="cpn.xsd">
    <name>zeus</name>
    <hosttype>master</hosttype>
    <hosts>
	<host>
	    <name>zeus</name>
	    <hosttype>master</hosttype>
	    <connection>
		<type>tcpip</type>
		<param>zeus.arlut.utexas.edu</param>
	    </connection>
	</host>
	<host>
	    <name>metis</name>
	    <hosttype>slave</hosttype>
	    <connection>
		<type>tcpip</type>
		<param>metis.arlut.utexas.edu</param>
	    </connection>
	</host>
	<host>
	    <name>syrinx</name>
	    <hosttype>slave</hosttype>
	    <connection>
		<type>tcpip</type>
		<param>syrinx.arlut.utexas.edu</param>
	    </connection>
	</host>
    </hosts>
    <nodes>
	<node>
	    <name>A</name>
	    <type>TypeA</type>
	    <param>use uint64</param>
	</node>
	<node>
	    <name>B</name>
	    <type>TypeB</type>
	</node>
	<node>
	    <name>C</name>
	    <type>TypeA</type>
	    <param>use float64</param>
	</node>
    </nodes>
    <queues>
	<queue>
	    <name>Queue A to B</name>
	    <type>CPN::ThresholdQueue</type>
	    <datatype>uint64</datatype>
	    <size>1024</size>
	    <maxThreshold>512</maxThreshold>
	    <channels>1</channels>
	    <writer>
		<node>A</node>
		<port>uint64 out</port>
	    </writer>
	    <reader>
		<node>B</node>
		<port>uint64 input</port>
	    </reader>
	</queue>
	<queue>
	    <name>Queue C to B</name>
	    <type>CPN::ThresholdQueue</type>
	    <datatype>float64</datatype>
	    <size>1024</size>
	    <maxThreshold>512</maxThreshold>
	    <channels>1</channels>
	    <writer>
		<node>C</node>
		<port>float64 out</port>
	    </writer>
	    <reader>
		<node>B</node>
		<port>float64 input</port>
	    </reader>
	</queue>
    </queues>
</hostprog>

=== GregoryEAllen/cpn/libraries/xmlcpn/xml/ExampleHostmap.xml
<?xml version="1.0"?>
<hostmap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="cpn.xsd">
    <host>
	<name>zeus</name>
	<node>A</node>
	<node>B</node>
	<node>C</node>
    </host>
    <host>
	<name>metis</name>
    </host>
    <host>
	<name>syrinx</name>
    </host>
</hostmap>

=== GregoryEAllen/cpn/libraries/xmlcpn/xml/ExampleHostprog_syrinx.xml
<?xml version="1.0"?>
<hostprog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="cpn.xsd">
    <name>syrinx</name>
    <hosttype>slave</hosttype>
    <hosts>
	<host>
	    <name>zeus</name>
	    <hosttype>master</hosttype>
	    <connection>
		<type>tcpip</type>
		<param>zeus.arlut.utexas.edu</param>
	    </connection>
	</host>
	<host>
	    <name>metis</name>
	    <hosttype>slave</hosttype>
	    <connection>
		<type>tcpip</type>
		<param>metis.arlut.utexas.edu</param>
	    </connection>
	</host>
	<host>
	    <name>syrinx</name>
	    <hosttype>slave</hosttype>
	    <connection>
		<type>tcpip</type>
		<param>syrinx.arlut.utexas.edu</param>
	    </connection>
	</host>
    </hosts>
    <nodes>
    </nodes>
    <queues>
    </queues>
</hostprog>

=== GregoryEAllen/cpn/test/cpntest/XMLLoaderTest.xml
<?xml version="1.0"?>
<hostprog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="cpn.xsd">
    <name>zeus</name>
    <hosttype>master</hosttype>
    <hosts>
        <host>
	    <name>zeus</name>
	    <hosttype>master</hosttype>
	    <connection>
		<type>tcpip</type>
		<param>zeus.arlut.utexas.edu</param>
	    </connection>
	</host>
    </hosts>
    <nodes>
	<node>
	    <name>A</name>
	    <type>MockNode</type>
	    <param>source</param>
	</node>
	<node>
	    <name>B</name>
	    <type>MockNode</type>
	    <param>transmute</param>
	</node>
	<node>
	    <name>C</name>
	    <type>MockNode</type>
	    <param>sink</param>
	</node>
    </nodes>
    <queues>
	<queue>
	    <name>Queue A to B</name>
	    <type>CPN::ThresholdQueue</type>
	    <datatype>uint64</datatype>
	    <size>1024</size>
	    <maxThreshold>512</maxThreshold>
	    <channels>1</channels>
	    <writer>
		<node>A</node>
		<port>y</port>
	    </writer>
	    <reader>
		<node>B</node>
		<port>x</port>
	    </reader>
	</queue>
	<queue>
	    <name>Queue B to C</name>
	    <type>CPN::ThresholdQueue</type>
	    <datatype>uint64</datatype>
	    <size>1024</size>
	    <maxThreshold>512</maxThreshold>
	    <channels>1</channels>
	    <writer>
		<node>B</node>
		<port>y</port>
	    </writer>
	    <reader>
		<node>C</node>
		<port>x</port>
	    </reader>
	</queue>
    </queues>
</hostprog>
